### ISSUE TITLE
Serializing a string with escaped characters adds an extra \

### ISSUE THREAD

**Issue by gatesphere** [stevedekorte/io#207]
Example:

```
Io> "\n" serialized
==> "\\n"
```

Not sure how to get around this...

**Comment by AlesTsurko** [comment]
The meaning of the serialization process is to get storable version of an object. If you would like to store an escaped character contained in a string, you should prepend it with a slash character so that after deserialization you'll get the same string.
Without the `\` before `\n` you'd lose `\n` character somewhere during serialization/deserialization of a string, because the character would be interpreted.
@stevedekorte looks like this can be closed too.

**Comment by stevedekorte** [comment]
thanks Ales
