### ISSUE TITLE
list(), List, map(), Map not consistant

### ISSUE THREAD

**Issue by krainboltgreene** [stevedekorte/io#209]
Consider the following:

  1. Io has a List object, which is a list of objects
  2. Io has a Map object, which has a list of keys and values, each of which can be any object

And now an example of where the confusion begins:

``` io
list(1, 2, 3, 4)
#=> list(1, 2, 3, 4), a new List object with 4 nodes

map("key", "value", 1, 4)
#=>  Exception: Object does not respond to 'map'

list(1, 2, 3) map(...)
#=> A List object, not a Map object
```

**Comment by stevedekorte** [comment]
FWIW, I agree Dictionary is a good name as it's abstract doesn't specify it's internal data structure a HashTable would (though it would be fine to have a HashTable proto that implemented the same abstract protocol so you could chose it if you wanted that data structure). I think I chose Map because it was similar and shorter and that seemed like a decent tradeoff. Dictionary would have kept with the Smalltalk/ObjC naming convention.

Btw, is there any standard lib that has a better set of collection classes than Smalltalk?
