### ISSUE TITLE
Cant link on OSX

### ISSUE THREAD

**Issue by radare** [stevedekorte/io#279]
```
Linking CXX shared library _build/dll/libIoObjcBridge.dylib
ld: library not found for -lIoYajl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [addons/ObjcBridge/_build/dll/libIoObjcBridge.dylib] Error 1
make[1]: *** [addons/ObjcBridge/CMakeFiles/IoObjcBridge.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by perfaram** [comment]
Same here...

**Comment by timup** [comment]
experiencing:

    [ 73%] Built target IoSocket
    Linking C shared library _build/dll/libIoObjcBridge.dylib
    ld: library not found for -lIoYajl
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [addons/ObjcBridge/_build/dll/libIoObjcBridge.dylib] Error 1
    make[1]: *** [addons/ObjcBridge/CMakeFiles/IoObjcBridge.dir/all] Error 2
    make: *** [all] Error 2

tried:
https://github.com/stevedekorte/io/issues/148

Same error with yajl installed.

**Comment by stevedekorte** [comment]
Hm, that's just for the Objc Bridge addon. Does the main io binary still build?

**Comment by radare** [comment]
Yes. it's in `build/_build/binaries/io`

**Comment by apjanke** [comment]
For me, this happens if `yajl` is not installed on the system. The `ObjcBridge` addon depends on `IoYajl`/the Yajl addon, and the Yajl addon depends on `yajl` being installed. The `Yajl` addon checks whether `yajl` is installed, and skips building if it is not installed. But the `ObjcBridge` addon does not check for whether `yajl` and/or the `Yajl` addon were installed/built, so it attempts to build regardless, and you get a link error.

Here's a PR to avoid the link error and still get a successful build when `yajl` is not installed (just without the ObjcBridge addon): #383.
