### ISSUE TITLE
"Object protos"  block the terminal

### ISSUE THREAD

**Issue by firemiles** [stevedekorte/io#301]
The terminal was blocked when I type the "Object protos“ in interactive terminal. Is it normal or bug?
![image](https://cloud.githubusercontent.com/assets/3798688/8155519/9db8d850-1377-11e5-9616-a4fe49adce98.png)

**Comment by peterhull90** [comment]
I think this is definitely undesirable behaviour. 
The cause is a list which indirectly contains itself.
It should output something like this:
```
Io> Object protos
==> list( Object_0x89782e8:
  Lobby            = Object_0x89782e8
  Protos           = Object_0x8978218
  _                = list(...)
  exit             = method(...)
  forward          = method(...)
  set_             = method(...)
)
```
The problem is the `_` slot, which contains the result of the last result from the command line. In this case it contains the list it's trying to print out, so it just recurses deeper and deeper without end.

The printed values of each slot are taken from `asSimpleString`, which should only be a brief version of the value. Unfortunately, `List`'s implementation calls to `asString` which tries to produce the full representation, hence the recursion.

In general, working with a list that contains itself is always going to be problematic but maybe a different implementation of `asSimpleString` for `List` could solve this particular issue.

I produced the text above by simply changing the implementation of `asSimpleString`:
```
List asSimpleString = "list(...)"
```
This may be a bit simplistic?

**Comment by peterhull90** [comment]
I think this can be closed, @firemiles  do you agree?
