### ISSUE TITLE
Build fails on OS X El Capitan w/ Homebrew

### ISSUE THREAD

**Issue by zephyrfalcon** [stevedekorte/io#333]
After installing all the dependencies, I'm getting the following when trying to install the latest version of Io (2015.11.11):

```
==> Installing io
==> Downloading https://github.com/stevedekorte/io/archive/2015.11.11.tar.gz
Already downloaded: /Users/hans/Library/Caches/Homebrew/io-2015.11.11.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_I
==> make
Last 15 lines from /Users/hans/Library/Logs/Homebrew/io/02.make:
      _getPrefDouble in unimotion.c.o
  "___CFConstantStringClassReference", referenced from:
      CFString in AppleLMU.c.o
      CFString in unimotion.c.o
      CFString in unimotion.c.o
      CFString in unimotion.c.o
      CFString in unimotion.c.o
      CFString in unimotion.c.o
      CFString in unimotion.c.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [addons/AppleSensors/_build/dll/libIoAppleSensors.dylib] Error 1
make[1]: *** [addons/AppleSensors/CMakeFiles/IoAppleSensors.dir/all] Error 2
make: *** [all] Error 2
```

Not sure if I'm doing anything wrong? I did make sure to do `brew update` and `brew doctor` beforehand. I do have an older version of Io installed, 2013.12.04, which is still there because the newer one didn't replace it.

**Comment by peterhull90** [comment]
How did you try to install it? I did a 

    $ brew install io

and that worked without errors. I've got a 2012 mac mini,

    $ uname -a
    Darwin iMac.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
    $ brew --version
    Homebrew 0.9.9 (git revision 96cbc; last commit 2016-06-17)
    Homebrew/homebrew-core (git revision cc28; last commit 2016-06-17)

**Comment by zephyrfalcon** [comment]
Huh... I did try to install it that way... I tried again today, getting rid of the old io install first with `homebrew unlink io`. Then 'brew install io` worked, although Homebrew did insist on installing its own flavor of Python 2.7, and then proceeded not to use it for Io. (I.e., Io has no access to Python.)

If I do `brew install io --with-python` it still gives me the aforementioned problem. So I guess the issue is with the Python addon somehow.

**Comment by peterhull90** [comment]
I'm not an expert with homebrew but I think the problem is more that installing `--with-python` causes homebrew to build Io from source rather than installing the binary bottle. If I download the corresponding tarball with `brew fetch io --build-from-source` and try to build it directly I get the same error you report.

It seems to me that the CMake script for the AppleSensor addon is missing a reference to the foundation library. If I patch addons/AppleSensors/CMakeLists.txt as follows
~~~
--- CMakeLists.txt	2015-10-22 21:36:35.000000000 +0100
+++ CMakeLists_PH.txt	2016-06-19 11:37:06.000000000 +0100
@@ -24,13 +24,14 @@
 )
 
 find_library(IOKIT IOKit)
+find_library(FOUNDATION Foundation)
 if (IOKIT)
   #add_executable(IoAppleSensors ${program_SOURCES})
 
   # Now build the shared library
   add_library(IoAppleSensors SHARED ${SRCS})
   add_dependencies(IoAppleSensors iovmall)
-  target_link_libraries(IoAppleSensors iovmall ${IOKIT})
+  target_link_libraries(IoAppleSensors iovmall ${IOKIT} ${FOUNDATION})
 
   # Install the addon to our global addons hierarchy.
   install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} DESTINATION lib/io/addons)
~~~
then it does compile successfully.

What do you think?

**Comment by cielavenir** [comment]
Great. You saved my life.

add this to `brew edit io`.

```
	patch :p0 do
		url 'https://raw.githubusercontent.com/cielavenir/homebrew-ciel/master/patch/io.patch'
		sha256 '62489be25589fff7e25c0f82775a36950d36c1ff691a07cb2ba85efc497e62dd'
	end
```

**Comment by PositiveControl** [comment]
Thanks @cielavenir!  Your patch solved my issue.

**Comment by bfontaine** [comment]
The patch is included in the Homebrew formula so this issue can be closed.
