### ISSUE TITLE
libIoOpenGL.dylib not linked properly to libIoBox.dylib

### ISSUE THREAD

**Issue by irskep** [stevedekorte/io#78]
Trying to run any addons/OpenGL/samples file:

```
Exception: Error loading object '/usr/local/Cellar/io/HEAD/lib/io/addons/OpenGL/_build/dll/libIoOpenGL.dylib': 'dlopen(/usr/local/Cellar/io/HEAD/lib/io/addons/OpenGL/_build/dll/libIoOpenGL.dylib, 10): Library not loaded: /tmp/homebrew-io-HEAD-m8jb/io-build/addons/Box/_build/dll/libIoBox.dylib
Referenced from: /usr/local/Cellar/io/HEAD/lib/io/addons/OpenGL/_build/dll/libIoOpenGL.dylib
Reason: image not found'
---------
open                                AddonLoader.io 71
Object OpenGL                        cylinder.io 4
CLI doFile                           Z_CLI.io 140
CLI run                              IoState_runCLI() 1
```

**Comment by AlesTsurko** [comment]
Unfortunately it wasn't fixed...
Looks like the problem is in the linking against `Box`. OpenGL can't find `libIoBox.dylib`. I've tried to copy `libIoBox.dylib` to `@runpath` and that fixed the issue. But something wrong in this linking at the root. Should `libIoOpenGL.dylib` be linked against `libIoBox.dylib` at all? Looks like an accidental link.

**Comment by AlesTsurko** [comment]
But then `OpenGL` rely on `Font`, that not installed at all.

**Comment by stevedekorte** [comment]
Would welcome a fix patch.

**Comment by AlesTsurko** [comment]
Already trying to fix it :)
